name = "Ansim"
uuid = "d95b3f39-30ea-4f44-875b-c3bf67c50329"
version = "0.1.0"
authors = ["Engon Ken Morel <engonken8@gmail.com>"]

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Revise = "3.8.1"
