# Generated By @claude AI. With

"""
BoxChars.jl

A Julia module providing easy access to Unicode box drawing characters and other
TUI-useful symbols. Import specific characters as needed.

Usage:
    import BoxChars as BC
    println(BC.TOP_LEFT * BC.HORIZONTAL * BC.TOP_RIGHT)
    println(BC.VERTICAL * " Hello " * BC.VERTICAL)
    println(BC.BOTTOM_LEFT * BC.HORIZONTAL * BC.BOTTOM_RIGHT)
"""
module BoxChars

# U+250x row
const HORIZONTAL_LIGHT = '─'          # U+2500
const HORIZONTAL_HEAVY = '━'          # U+2501
const VERTICAL_LIGHT = '│'            # U+2502
const VERTICAL_HEAVY = '┃'            # U+2503
const HORIZONTAL_TRIPLE_DASH = '┄'    # U+2504
const HORIZONTAL_HEAVY_TRIPLE_DASH = '┅' # U+2505
const VERTICAL_TRIPLE_DASH = '┆'      # U+2506
const VERTICAL_HEAVY_TRIPLE_DASH = '┇' # U+2507
const HORIZONTAL_QUAD_DASH = '┈'      # U+2508
const HORIZONTAL_HEAVY_QUAD_DASH = '┉' # U+2509
const VERTICAL_QUAD_DASH = '┊'        # U+250A
const VERTICAL_HEAVY_QUAD_DASH = '┋'  # U+250B
const TOP_LEFT_LIGHT = '┌'            # U+250C
const TOP_LEFT_HEAVY_DOWN_RIGHT = '┍' # U+250D
const TOP_LEFT_DOWN_HEAVY_RIGHT = '┎' # U+250E
const TOP_LEFT_HEAVY = '┏'            # U+250F

# U+251x row
const TOP_RIGHT_LIGHT = '┐'           # U+2510
const TOP_RIGHT_HEAVY_DOWN_LEFT = '┑' # U+2511
const TOP_RIGHT_DOWN_HEAVY_LEFT = '┒' # U+2512
const TOP_RIGHT_HEAVY = '┓'           # U+2513
const BOTTOM_LEFT_LIGHT = '└'         # U+2514
const BOTTOM_LEFT_HEAVY_UP_RIGHT = '┕' # U+2515
const BOTTOM_LEFT_UP_HEAVY_RIGHT = '┖' # U+2516
const BOTTOM_LEFT_HEAVY = '┗'         # U+2517
const BOTTOM_RIGHT_LIGHT = '┘'        # U+2518
const BOTTOM_RIGHT_HEAVY_UP_LEFT = '┙' # U+2519
const BOTTOM_RIGHT_UP_HEAVY_LEFT = '┚' # U+251A
const BOTTOM_RIGHT_HEAVY = '┛'        # U+251B
const TEE_LEFT_LIGHT = '├'            # U+251C
const TEE_LEFT_HEAVY_UP_DOWN = '┝'    # U+251D
const TEE_LEFT_UP_HEAVY_DOWN = '┞'    # U+251E
const TEE_LEFT_UP_DOWN_HEAVY = '┟'    # U+251F

# U+252x row
const TEE_LEFT_HEAVY_UP = '┠'         # U+2520
const TEE_LEFT_HEAVY_DOWN = '┡'       # U+2521
const TEE_LEFT_HEAVY_UP_RIGHT = '┢'   # U+2522
const TEE_LEFT_HEAVY = '┣'            # U+2523
const TEE_RIGHT_LIGHT = '┤'           # U+2524
const TEE_RIGHT_HEAVY_UP_DOWN = '┥'   # U+2525
const TEE_RIGHT_UP_HEAVY_DOWN = '┦'   # U+2526
const TEE_RIGHT_UP_DOWN_HEAVY = '┧'   # U+2527
const TEE_RIGHT_HEAVY_UP = '┨'        # U+2528
const TEE_RIGHT_HEAVY_DOWN = '┩'      # U+2529
const TEE_RIGHT_HEAVY_UP_LEFT = '┪'   # U+252A
const TEE_RIGHT_HEAVY = '┫'           # U+252B
const TEE_UP_LIGHT = '┬'              # U+252C
const TEE_UP_HEAVY_LEFT_RIGHT = '┭'   # U+252D
const TEE_UP_LEFT_HEAVY_RIGHT = '┮'   # U+252E
const TEE_UP_LEFT_RIGHT_HEAVY = '┯'   # U+252F

# U+253x row
const TEE_UP_HEAVY_LEFT = '┰'         # U+2530
const TEE_UP_HEAVY_RIGHT = '┱'        # U+2531
const TEE_UP_HEAVY_DOWN_RIGHT = '┲'   # U+2532
const TEE_UP_HEAVY = '┳'              # U+2533
const TEE_DOWN_LIGHT = '┴'            # U+2534
const TEE_DOWN_HEAVY_LEFT_RIGHT = '┵' # U+2535
const TEE_DOWN_LEFT_HEAVY_RIGHT = '┶' # U+2536
const TEE_DOWN_LEFT_RIGHT_HEAVY = '┷' # U+2537
const TEE_DOWN_HEAVY_LEFT = '┸'       # U+2538
const TEE_DOWN_HEAVY_RIGHT = '┹'      # U+2539
const TEE_DOWN_HEAVY_UP_RIGHT = '┺'   # U+253A
const TEE_DOWN_HEAVY = '┻'            # U+253B
const CROSS_LIGHT = '┼'               # U+253C
const CROSS_HEAVY_LEFT_RIGHT = '┽'    # U+253D
const CROSS_UP_HEAVY_DOWN = '┾'       # U+253E
const CROSS_UP_DOWN_HEAVY = '┿'       # U+253F

# U+254x row
const CROSS_HEAVY_UP = '╀'            # U+2540
const CROSS_HEAVY_DOWN = '╁'          # U+2541
const CROSS_HEAVY_LEFT = '╂'          # U+2542
const CROSS_HEAVY_RIGHT = '╃'         # U+2543
const CROSS_HEAVY_UP_DOWN = '╄'       # U+2544
const CROSS_HEAVY_LEFT_RIGHT_2 = '╅' # U+2545
const CROSS_HEAVY_UP_LEFT_RIGHT = '╆' # U+2546
const CROSS_HEAVY = '╇'               # U+2547
const CROSS_HEAVY_UP_HORIZONTAL = '╈' # U+2548
const CROSS_HEAVY_DOWN_HORIZONTAL = '╉' # U+2549
const CROSS_HEAVY_VERTICAL_LEFT = '╊' # U+254A
const CROSS_HEAVY_VERTICAL_RIGHT = '╋' # U+254B
const DASHED_2 = '╌'                  # U+254C
const DASHED_3 = '╍'                  # U+254D
const DASHED_4 = '╎'                  # U+254E
const DASHED_5 = '╏'                  # U+254F

# U+255x row - Double lines
const DOUBLE_HORIZONTAL = '═'         # U+2550
const DOUBLE_VERTICAL = '║'           # U+2551
const DOUBLE_TOP_LEFT = '╔'           # U+2554
const DOUBLE_TOP_LEFT_SINGLE_DOWN = '╓' # U+2553
const DOUBLE_TOP_LEFT_SINGLE_RIGHT = '╒' # U+2552
const DOUBLE_TOP_RIGHT = '╗'          # U+2557
const DOUBLE_TOP_RIGHT_SINGLE_DOWN = '╖' # U+2556
const DOUBLE_TOP_RIGHT_SINGLE_LEFT = '╕' # U+2555
const DOUBLE_BOTTOM_LEFT = '╚'        # U+255A
const DOUBLE_BOTTOM_LEFT_SINGLE_UP = '╙' # U+2559
const DOUBLE_BOTTOM_LEFT_SINGLE_RIGHT = '╘' # U+2558
const DOUBLE_BOTTOM_RIGHT = '╝'       # U+255D
const DOUBLE_BOTTOM_RIGHT_SINGLE_UP = '╜' # U+255C
const DOUBLE_BOTTOM_RIGHT_SINGLE_LEFT = '╛' # U+255B
const DOUBLE_TEE_LEFT = '╠'           # U+2560
const DOUBLE_TEE_LEFT_SINGLE_UP_DOWN = '╟' # U+255F

# U+256x row
const DOUBLE_TEE_LEFT_SINGLE_DOWN = '╞' # U+255E
const DOUBLE_TEE_RIGHT = '╣'          # U+2563
const DOUBLE_TEE_RIGHT_SINGLE_UP_DOWN = '╢' # U+2562
const DOUBLE_TEE_RIGHT_SINGLE_UP = '╡' # U+2561
const DOUBLE_TEE_UP = '╦'             # U+2566
const DOUBLE_TEE_UP_SINGLE_LEFT_RIGHT = '╥' # U+2565
const DOUBLE_TEE_UP_SINGLE_RIGHT = '╤' # U+2564
const DOUBLE_TEE_DOWN = '╩'           # U+2569
const DOUBLE_TEE_DOWN_SINGLE_LEFT_RIGHT = '╨' # U+2568
const DOUBLE_TEE_DOWN_SINGLE_RIGHT = '╧' # U+2567
const DOUBLE_CROSS = '╬'              # U+256C
const DOUBLE_CROSS_SINGLE_LEFT_RIGHT = '╫' # U+256B
const DOUBLE_CROSS_SINGLE_UP_DOWN = '╪' # U+256A
const ROUNDED_TOP_LEFT = '╭'          # U+256D
const ROUNDED_TOP_RIGHT = '╮'         # U+256E
const ROUNDED_BOTTOM_RIGHT = '╯'      # U+256F

# U+257x row
const ROUNDED_BOTTOM_LEFT = '╰'       # U+2570
const DIAGONAL_UP_RIGHT = '╱'         # U+2571
const DIAGONAL_DOWN_RIGHT = '╲'       # U+2572
const DIAGONAL_CROSS = '╳'            # U+2573
const HORIZONTAL_1 = '╴'              # U+2574
const VERTICAL_1 = '╵'                # U+2575
const HORIZONTAL_2 = '╶'              # U+2576
const VERTICAL_2 = '╷'                # U+2577
const HORIZONTAL_3 = '╸'              # U+2578
const VERTICAL_3 = '╹'                # U+2579
const HORIZONTAL_4 = '╺'              # U+257A
const VERTICAL_4 = '╻'                # U+257B
const HORIZONTAL_5 = '╼'              # U+257C
const VERTICAL_5 = '╽'                # U+257D
const HORIZONTAL_6 = '╾'              # U+257E
const VERTICAL_6 = '╿'                # U+257F

# Convenient aliases for most common characters
const H = HORIZONTAL_LIGHT
const V = VERTICAL_LIGHT
const TL = TOP_LEFT_LIGHT
const TR = TOP_RIGHT_LIGHT
const BL = BOTTOM_LEFT_LIGHT
const BR = BOTTOM_RIGHT_LIGHT
# const CROSS = CROSS_LIGHT

# More readable aliases
const HORIZONTAL = HORIZONTAL_LIGHT
const VERTICAL = VERTICAL_LIGHT
const TOP_LEFT = TOP_LEFT_LIGHT
const TOP_RIGHT = TOP_RIGHT_LIGHT
const BOTTOM_LEFT = BOTTOM_LEFT_LIGHT
const BOTTOM_RIGHT = BOTTOM_RIGHT_LIGHT

# ============================================================================
# ADDITIONAL TUI CHARACTERS
# ============================================================================

# Block Elements (U+2580-U+259F)
const UPPER_HALF_BLOCK = '▀'          # U+2580
const LOWER_ONE_EIGHTH_BLOCK = '▁'    # U+2581
const LOWER_ONE_QUARTER_BLOCK = '▂'   # U+2582
const LOWER_THREE_EIGHTHS_BLOCK = '▃' # U+2583
const LOWER_HALF_BLOCK = '▄'          # U+2584
const LOWER_FIVE_EIGHTHS_BLOCK = '▅'  # U+2585
const LOWER_THREE_QUARTERS_BLOCK = '▆' # U+2586
const LOWER_SEVEN_EIGHTHS_BLOCK = '▇' # U+2587
const FULL_BLOCK = '█'                # U+2588
const LEFT_SEVEN_EIGHTHS_BLOCK = '▉'  # U+2589
const LEFT_THREE_QUARTERS_BLOCK = '▊' # U+258A
const LEFT_FIVE_EIGHTHS_BLOCK = '▋'   # U+258B
const LEFT_HALF_BLOCK = '▌'           # U+258C
const LEFT_THREE_EIGHTHS_BLOCK = '▍'  # U+258D
const LEFT_ONE_QUARTER_BLOCK = '▎'    # U+258E
const LEFT_ONE_EIGHTH_BLOCK = '▏'     # U+258F
const RIGHT_HALF_BLOCK = '▐'          # U+2590
const LIGHT_SHADE = '░'               # U+2591
const MEDIUM_SHADE = '▒'              # U+2592
const DARK_SHADE = '▓'                # U+2593
const UPPER_ONE_EIGHTH_BLOCK = '▔'    # U+2594
const RIGHT_ONE_EIGHTH_BLOCK = '▕'    # U+2595

# Quadrant blocks
const QUADRANT_LOWER_LEFT = '▖'       # U+2596
const QUADRANT_LOWER_RIGHT = '▗'      # U+2597
const QUADRANT_UPPER_LEFT = '▘'       # U+2598
const QUADRANT_UPPER_LEFT_LOWER_LEFT_LOWER_RIGHT = '▙' # U+2599
const QUADRANT_UPPER_LEFT_LOWER_RIGHT = '▚' # U+259A
const QUADRANT_UPPER_LEFT_UPPER_RIGHT_LOWER_LEFT = '▛' # U+259B
const QUADRANT_UPPER_LEFT_UPPER_RIGHT_LOWER_RIGHT = '▜' # U+259C
const QUADRANT_UPPER_RIGHT = '▝'      # U+259D
const QUADRANT_UPPER_RIGHT_LOWER_LEFT = '▞' # U+259E
const QUADRANT_UPPER_RIGHT_LOWER_LEFT_LOWER_RIGHT = '▟' # U+259F

# Geometric Shapes (U+25A0-U+25FF)
const BLACK_SQUARE = '■'              # U+25A0
const WHITE_SQUARE = '□'              # U+25A1
const WHITE_SQUARE_SMALL = '▫'        # U+25AB
const BLACK_SQUARE_SMALL = '▪'        # U+25AA
const BLACK_RECTANGLE = '▬'           # U+25AC
const WHITE_RECTANGLE = '▭'           # U+25AD
const BLACK_VERTICAL_RECTANGLE = '▮'  # U+25AE
const WHITE_VERTICAL_RECTANGLE = '▯'  # U+25AF

# Triangles
const BLACK_UP_TRIANGLE = '▲'         # U+25B2
const WHITE_UP_TRIANGLE = '△'         # U+25B3
const BLACK_UP_TRIANGLE_SMALL = '▴'   # U+25B4
const WHITE_UP_TRIANGLE_SMALL = '▵'   # U+25B5
const BLACK_RIGHT_TRIANGLE = '▶'      # U+25B6
const WHITE_RIGHT_TRIANGLE = '▷'      # U+25B7
const BLACK_RIGHT_TRIANGLE_SMALL = '▸' # U+25B8
const WHITE_RIGHT_TRIANGLE_SMALL = '▹' # U+25B9
const BLACK_DOWN_TRIANGLE = '▼'       # U+25BC
const WHITE_DOWN_TRIANGLE = '▽'       # U+25BD
const BLACK_DOWN_TRIANGLE_SMALL = '▾' # U+25BE
const WHITE_DOWN_TRIANGLE_SMALL = '▿' # U+25BF
const BLACK_LEFT_TRIANGLE = '◀'       # U+25C0
const WHITE_LEFT_TRIANGLE = '◁'       # U+25C1
const BLACK_LEFT_TRIANGLE_SMALL = '◂' # U+25C2
const WHITE_LEFT_TRIANGLE_SMALL = '◃' # U+25C3

# Circles
const BLACK_CIRCLE = '●'              # U+25CF
const WHITE_CIRCLE = '○'              # U+25CB
const DOTTED_CIRCLE = '◌'             # U+25CC
const CIRCLE_LEFT_HALF_BLACK = '◐'    # U+25D0
const CIRCLE_RIGHT_HALF_BLACK = '◑'   # U+25D1
const CIRCLE_LOWER_HALF_BLACK = '◒'   # U+25D2
const CIRCLE_UPPER_HALF_BLACK = '◓'   # U+25D3
const CIRCLE_UPPER_RIGHT_QUADRANT_BLACK = '◔' # U+25D4
const CIRCLE_ALL_BUT_UPPER_LEFT_QUADRANT_BLACK = '◕' # U+25D5
const LEFT_HALF_BLACK_CIRCLE = '◖'    # U+25D6
const RIGHT_HALF_BLACK_CIRCLE = '◗'   # U+25D7
const INVERSE_BULLET = '◘'            # U+25D8
const INVERSE_WHITE_CIRCLE = '◙'      # U+25D9
const UPPER_HALF_INVERSE_WHITE_CIRCLE = '◚' # U+25DA
const LOWER_HALF_INVERSE_WHITE_CIRCLE = '◛' # U+25DB

# Diamonds and other shapes
const BLACK_DIAMOND = '◆'             # U+25C6
const WHITE_DIAMOND = '◇'             # U+25C7
const BLACK_DIAMOND_SMALL = '◈'       # U+25C8
const WHITE_DIAMOND_SMALL = '◉'       # U+25C9
const LOZENGE = '◊'                   # U+25CA
const WHITE_CIRCLE_DOT = '⊙'          # U+2299 (from Mathematical Operators)
const BULLSEYE = '◎'                  # U+25CE

# Arrows (U+2190-U+21FF) - Basic set
const LEFTWARDS_ARROW = '←'           # U+2190
const UPWARDS_ARROW = '↑'             # U+2191
const RIGHTWARDS_ARROW = '→'          # U+2192
const DOWNWARDS_ARROW = '↓'           # U+2193
const LEFT_RIGHT_ARROW = '↔'          # U+2194
const UP_DOWN_ARROW = '↕'             # U+2195
const NORTH_WEST_ARROW = '↖'          # U+2196
const NORTH_EAST_ARROW = '↗'          # U+2197
const SOUTH_EAST_ARROW = '↘'          # U+2198
const SOUTH_WEST_ARROW = '↙'          # U+2199
const LEFTWARDS_ARROW_HOOK = '↩'      # U+2329
const RIGHTWARDS_ARROW_HOOK = '↪'     # U+232A

# Double arrows
const LEFTWARDS_DOUBLE_ARROW = '⇐'    # U+21D0
const UPWARDS_DOUBLE_ARROW = '⇑'      # U+21D1
const RIGHTWARDS_DOUBLE_ARROW = '⇒'   # U+21D2
const DOWNWARDS_DOUBLE_ARROW = '⇓'    # U+21D3
const LEFT_RIGHT_DOUBLE_ARROW = '⇔'   # U+21D4
const UP_DOWN_DOUBLE_ARROW = '⇕'      # U+21D5

# Heavy arrows
const HEAVY_LEFTWARDS_ARROW = '⬅'     # U+2B05
const HEAVY_UPWARDS_ARROW = '⬆'       # U+2B06
const HEAVY_RIGHTWARDS_ARROW = '➡'    # U+27A1
const HEAVY_DOWNWARDS_ARROW = '⬇'     # U+2B07

# Miscellaneous Symbols (U+2600-U+26FF)
const BLACK_STAR = '★'                # U+2605
const WHITE_STAR = '☆'                # U+2606
const BLACK_HEART = '♥'               # U+2665
const WHITE_HEART = '♡'               # U+2661
const BLACK_CLUB = '♣'                # U+2663
const WHITE_CLUB = '♧'                # U+2667
const BLACK_DIAMOND_SUIT = '♦'        # U+2666
const WHITE_DIAMOND_SUIT = '♢'        # U+2662
const BLACK_SPADE = '♠'               # U+2660
const WHITE_SPADE = '♤'               # U+2664

# Musical symbols
const EIGHTH_NOTE = '♪'               # U+266A
const BEAMED_EIGHTH_NOTES = '♫'       # U+266B
const BEAMED_SIXTEENTH_NOTES = '♬'    # U+266C
const MUSIC_FLAT_SIGN = '♭'           # U+266D
const MUSIC_NATURAL_SIGN = '♮'        # U+266E
const MUSIC_SHARP_SIGN = '♯'          # U+266F

# Gender and misc symbols
const MALE_SIGN = '♂'                 # U+2642
const FEMALE_SIGN = '♀'               # U+2640
const MERCURY = '☿'                   # U+263F
const VENUS = '♀'                     # U+2640 (same as female)
const EARTH = '♁'                     # U+2641
const MARS = '♂'                      # U+2642 (same as male)
const JUPITER = '♃'                   # U+2643
const SATURN = '♄'                    # U+2644
const URANUS = '♅'                    # U+2645
const NEPTUNE = '♆'                   # U+2646
const PLUTO = '♇'                     # U+2647

# Weather symbols
const BLACK_SUN_WITH_RAYS = '☀'       # U+2600
const CLOUD = '☁'                     # U+2601
const UMBRELLA = '☂'                  # U+2602
const SNOWMAN = '☃'                   # U+2603
const COMET = '☄'                     # U+2604

# Miscellaneous technical (U+2300-U+23FF)
const DIAMETER_SIGN = '⌀'             # U+2300
const ELECTRIC_ARROW = '⌁'            # U+2301
const HOUSE = '⌂'                     # U+2302
const UP_ARROWHEAD = '⌃'              # U+2303
const DOWN_ARROWHEAD = '⌄'            # U+2304
const PROJECTIVE = '⌅'                # U+2305
const PERSPECTIVE = '⌆'               # U+2306
const WAVY_LINE = '⌇'                 # U+2307

# Technical symbols
const LEFT_CEILING = '⌈'              # U+2308
const RIGHT_CEILING = '⌉'             # U+2309
const LEFT_FLOOR = '⌊'                # U+230A
const RIGHT_FLOOR = '⌋'               # U+230B
const CROP = '⌐'                      # U+2310
const SQUARE_LOZENGE = '⌑'            # U+2311
const ARC = '⌒'                       # U+2312
const SEGMENT = '⌓'                   # U+2313
const SECTOR = '⌔'                    # U+2314

# Brackets and parentheses
const LEFT_ANGLE_BRACKET = '⟨'        # U+27E8
const RIGHT_ANGLE_BRACKET = '⟩'       # U+27E9
const MATHEMATICAL_LEFT_ANGLE_BRACKET = '⟪' # U+27EA
const MATHEMATICAL_RIGHT_ANGLE_BRACKET = '⟫' # U+27EB

# Control pictures (U+2400-U+243F)
const SYMBOL_FOR_NULL = '␀'           # U+2400
const SYMBOL_FOR_START_OF_HEADING = '␁' # U+2401
const SYMBOL_FOR_START_OF_TEXT = '␂'  # U+2402
const SYMBOL_FOR_END_OF_TEXT = '␃'    # U+2403
const SYMBOL_FOR_END_OF_TRANSMISSION = '␄' # U+2404
const SYMBOL_FOR_ENQUIRY = '␅'        # U+2405
const SYMBOL_FOR_ACKNOWLEDGE = '␆'    # U+2406
const SYMBOL_FOR_BELL = '␇'           # U+2407
const SYMBOL_FOR_BACKSPACE = '␈'      # U+2408
const SYMBOL_FOR_HORIZONTAL_TAB = '␉' # U+2409
const SYMBOL_FOR_LINE_FEED = '␊'      # U+240A
const SYMBOL_FOR_VERTICAL_TAB = '␋'   # U+240B
const SYMBOL_FOR_FORM_FEED = '␌'      # U+240C
const SYMBOL_FOR_CARRIAGE_RETURN = '␍' # U+240D
const SYMBOL_FOR_SHIFT_OUT = '␎'      # U+240E
const SYMBOL_FOR_SHIFT_IN = '␏'       # U+240F
const SYMBOL_FOR_DATA_LINK_ESCAPE = '␐' # U+2410
const SYMBOL_FOR_DEVICE_CONTROL_ONE = '␑' # U+2411
const SYMBOL_FOR_DEVICE_CONTROL_TWO = '␒' # U+2412
const SYMBOL_FOR_DEVICE_CONTROL_THREE = '␓' # U+2413
const SYMBOL_FOR_DEVICE_CONTROL_FOUR = '␔' # U+2414
const SYMBOL_FOR_NEGATIVE_ACKNOWLEDGE = '␕' # U+2415
const SYMBOL_FOR_SYNCHRONOUS_IDLE = '␖' # U+2416
const SYMBOL_FOR_END_OF_TRANSMISSION_BLOCK = '␗' # U+2417
const SYMBOL_FOR_CANCEL = '␘'         # U+2418
const SYMBOL_FOR_END_OF_MEDIUM = '␙'  # U+2419
const SYMBOL_FOR_SUBSTITUTE = '␚'     # U+241A
const SYMBOL_FOR_ESCAPE = '␛'         # U+241B
const SYMBOL_FOR_FILE_SEPARATOR = '␜' # U+241C
const SYMBOL_FOR_GROUP_SEPARATOR = '␝' # U+241D
const SYMBOL_FOR_RECORD_SEPARATOR = '␞' # U+241E
const SYMBOL_FOR_UNIT_SEPARATOR = '␟' # U+241F
const SYMBOL_FOR_SPACE = '␠'          # U+2420
const SYMBOL_FOR_DELETE = '␡'         # U+2421

# Mathematical operators (useful subset)
const MINUS_SIGN = '−'                # U+2212
const PLUS_MINUS = '±'                # U+00B1
const MULTIPLICATION_SIGN = '×'       # U+00D7
const DIVISION_SIGN = '÷'             # U+00F7
const NOT_EQUAL_TO = '≠'              # U+2260
const IDENTICAL_TO = '≡'              # U+2261
const LESS_THAN_OR_EQUAL_TO = '≤'     # U+2264
const GREATER_THAN_OR_EQUAL_TO = '≥'  # U+2265
const MUCH_LESS_THAN = '≪'            # U+226A
const MUCH_GREATER_THAN = '≫'         # U+226B
const INFINITY = '∞'                  # U+221E
const PARTIAL_DIFFERENTIAL = '∂'      # U+2202
const INTEGRAL = '∫'                  # U+222B
const DOUBLE_INTEGRAL = '∬'           # U+222C
const TRIPLE_INTEGRAL = '∭'           # U+222D
const CONTOUR_INTEGRAL = '∮'          # U+222E
const SURFACE_INTEGRAL = '∯'          # U+222F
const VOLUME_INTEGRAL = '∰'           # U+2230
const CLOCKWISE_INTEGRAL = '∱'        # U+2231
const CLOCKWISE_CONTOUR_INTEGRAL = '∲' # U+2232
const ANTICLOCKWISE_CONTOUR_INTEGRAL = '∳' # U+2233

# Greek letters (commonly used in TUIs)
const ALPHA = 'α'                     # U+03B1
const BETA = 'β'                      # U+03B2
const GAMMA = 'γ'                     # U+03B3
const DELTA = 'δ'                     # U+03B4
const EPSILON = 'ε'                   # U+03B5
const ZETA = 'ζ'                      # U+03B6
const ETA = 'η'                       # U+03B7
const THETA = 'θ'                     # U+03B8
const IOTA = 'ι'                      # U+03B9
const KAPPA = 'κ'                     # U+03BA
const LAMBDA = 'λ'                    # U+03BB
const MU = 'μ'                        # U+03BC
const NU = 'ν'                        # U+03BD
const XI = 'ξ'                        # U+03BE
const OMICRON = 'ο'                   # U+03BF
const PI = 'π'                        # U+03C0
const RHO = 'ρ'                       # U+03C1
const SIGMA = 'σ'                     # U+03C3
const TAU = 'τ'                       # U+03C4
const UPSILON = 'υ'                   # U+03C5
const PHI = 'φ'                       # U+03C6
const CHI = 'χ'                       # U+03C7
const PSI = 'ψ'                       # U+03C8
const OMEGA = 'ω'                     # U+03C9

# Common TUI status indicators
const CHECKMARK = '✓'                 # U+2713
const HEAVY_CHECKMARK = '✔'           # U+2714
const MULTIPLICATION_X = '✕'          # U+2715
const HEAVY_MULTIPLICATION_X = '✖'    # U+2716
const BALLOT_X = '✗'                  # U+2717
const HEAVY_BALLOT_X = '✘'            # U+2718

# More useful symbols
const BULLET = '•'                    # U+2022
const TRIANGULAR_BULLET = '‣'         # U+2023
const HYPHEN_BULLET = '⁃'             # U+2043
const WHITE_BULLET = '◦'              # U+25E6
const MIDDLE_DOT = '·'                # U+00B7
const ONE_DOT_LEADER = '․'            # U+2024
const TWO_DOT_LEADER = '‥'            # U+2025
const HORIZONTAL_ELLIPSIS = '…'       # U+2026
const VERTICAL_ELLIPSIS = '⋮'         # U+22EE

# Common aliases for frequently used characters
const SOLID_BLOCK = FULL_BLOCK
const EMPTY_BLOCK = WHITE_SQUARE
const DOT = BULLET
const CHECK = CHECKMARK
const CROSS = MULTIPLICATION_X
const ELLIPSIS = HORIZONTAL_ELLIPSIS

end # module
