"""
Generated by @Claude AI

BoxChars.jl

A Julia module providing easy access to Unicode box drawing characters.
All characters are exported for convenient use in text-based graphics,
tables, and visual layouts.

Usage:
    using BoxChars
    println(TOP_LEFT * HORIZONTAL * TOP_RIGHT)
    println(VERTICAL * " Hello " * VERTICAL)
    println(BOTTOM_LEFT * HORIZONTAL * BOTTOM_RIGHT)
"""
module BoxChars

# U+250x row
const HORIZONTAL_LIGHT = '─'          # U+2500
const HORIZONTAL_HEAVY = '━'          # U+2501
const VERTICAL_LIGHT = '│'            # U+2502
const VERTICAL_HEAVY = '┃'            # U+2503
const HORIZONTAL_TRIPLE_DASH = '┄'    # U+2504
const HORIZONTAL_HEAVY_TRIPLE_DASH = '┅' # U+2505
const VERTICAL_TRIPLE_DASH = '┆'      # U+2506
const VERTICAL_HEAVY_TRIPLE_DASH = '┇' # U+2507
const HORIZONTAL_QUAD_DASH = '┈'      # U+2508
const HORIZONTAL_HEAVY_QUAD_DASH = '┉' # U+2509
const VERTICAL_QUAD_DASH = '┊'        # U+250A
const VERTICAL_HEAVY_QUAD_DASH = '┋'  # U+250B
const TOP_LEFT_LIGHT = '┌'            # U+250C
const TOP_LEFT_HEAVY_DOWN_RIGHT = '┍' # U+250D
const TOP_LEFT_DOWN_HEAVY_RIGHT = '┎' # U+250E
const TOP_LEFT_HEAVY = '┏'            # U+250F

# U+251x row
const TOP_RIGHT_LIGHT = '┐'           # U+2510
const TOP_RIGHT_HEAVY_DOWN_LEFT = '┑' # U+2511
const TOP_RIGHT_DOWN_HEAVY_LEFT = '┒' # U+2512
const TOP_RIGHT_HEAVY = '┓'           # U+2513
const BOTTOM_LEFT_LIGHT = '└'         # U+2514
const BOTTOM_LEFT_HEAVY_UP_RIGHT = '┕' # U+2515
const BOTTOM_LEFT_UP_HEAVY_RIGHT = '┖' # U+2516
const BOTTOM_LEFT_HEAVY = '┗'         # U+2517
const BOTTOM_RIGHT_LIGHT = '┘'        # U+2518
const BOTTOM_RIGHT_HEAVY_UP_LEFT = '┙' # U+2519
const BOTTOM_RIGHT_UP_HEAVY_LEFT = '┚' # U+251A
const BOTTOM_RIGHT_HEAVY = '┛'        # U+251B
const TEE_LEFT_LIGHT = '├'            # U+251C
const TEE_LEFT_HEAVY_UP_DOWN = '┝'    # U+251D
const TEE_LEFT_UP_HEAVY_DOWN = '┞'    # U+251E
const TEE_LEFT_UP_DOWN_HEAVY = '┟'    # U+251F

# U+252x row
const TEE_LEFT_HEAVY_UP = '┠'         # U+2520
const TEE_LEFT_HEAVY_DOWN = '┡'       # U+2521
const TEE_LEFT_HEAVY_UP_RIGHT = '┢'   # U+2522
const TEE_LEFT_HEAVY = '┣'            # U+2523
const TEE_RIGHT_LIGHT = '┤'           # U+2524
const TEE_RIGHT_HEAVY_UP_DOWN = '┥'   # U+2525
const TEE_RIGHT_UP_HEAVY_DOWN = '┦'   # U+2526
const TEE_RIGHT_UP_DOWN_HEAVY = '┧'   # U+2527
const TEE_RIGHT_HEAVY_UP = '┨'        # U+2528
const TEE_RIGHT_HEAVY_DOWN = '┩'      # U+2529
const TEE_RIGHT_HEAVY_UP_LEFT = '┪'   # U+252A
const TEE_RIGHT_HEAVY = '┫'           # U+252B
const TEE_UP_LIGHT = '┬'              # U+252C
const TEE_UP_HEAVY_LEFT_RIGHT = '┭'   # U+252D
const TEE_UP_LEFT_HEAVY_RIGHT = '┮'   # U+252E
const TEE_UP_LEFT_RIGHT_HEAVY = '┯'   # U+252F

# U+253x row
const TEE_UP_HEAVY_LEFT = '┰'         # U+2530
const TEE_UP_HEAVY_RIGHT = '┱'        # U+2531
const TEE_UP_HEAVY_DOWN_RIGHT = '┲'   # U+2532
const TEE_UP_HEAVY = '┳'              # U+2533
const TEE_DOWN_LIGHT = '┴'            # U+2534
const TEE_DOWN_HEAVY_LEFT_RIGHT = '┵' # U+2535
const TEE_DOWN_LEFT_HEAVY_RIGHT = '┶' # U+2536
const TEE_DOWN_LEFT_RIGHT_HEAVY = '┷' # U+2537
const TEE_DOWN_HEAVY_LEFT = '┸'       # U+2538
const TEE_DOWN_HEAVY_RIGHT = '┹'      # U+2539
const TEE_DOWN_HEAVY_UP_RIGHT = '┺'   # U+253A
const TEE_DOWN_HEAVY = '┻'            # U+253B
const CROSS_LIGHT = '┼'               # U+253C
const CROSS_HEAVY_LEFT_RIGHT = '┽'    # U+253D
const CROSS_UP_HEAVY_DOWN = '┾'       # U+253E
const CROSS_UP_DOWN_HEAVY = '┿'       # U+253F

# U+254x row
const CROSS_HEAVY_UP = '╀'            # U+2540
const CROSS_HEAVY_DOWN = '╁'          # U+2541
const CROSS_HEAVY_LEFT = '╂'          # U+2542
const CROSS_HEAVY_RIGHT = '╃'         # U+2543
const CROSS_HEAVY_UP_DOWN = '╄'       # U+2544
const CROSS_HEAVY_LEFT_RIGHT_2 = '╅' # U+2545
const CROSS_HEAVY_UP_LEFT_RIGHT = '╆' # U+2546
const CROSS_HEAVY = '╇'               # U+2547
const CROSS_HEAVY_UP_HORIZONTAL = '╈' # U+2548
const CROSS_HEAVY_DOWN_HORIZONTAL = '╉' # U+2549
const CROSS_HEAVY_VERTICAL_LEFT = '╊' # U+254A
const CROSS_HEAVY_VERTICAL_RIGHT = '╋' # U+254B
const DASHED_2 = '╌'                  # U+254C
const DASHED_3 = '╍'                  # U+254D
const DASHED_4 = '╎'                  # U+254E
const DASHED_5 = '╏'                  # U+254F

# U+255x row - Double lines
const DOUBLE_HORIZONTAL = '═'         # U+2550
const DOUBLE_VERTICAL = '║'           # U+2551
const DOUBLE_TOP_LEFT = '╔'           # U+2554
const DOUBLE_TOP_LEFT_SINGLE_DOWN = '╓' # U+2553
const DOUBLE_TOP_LEFT_SINGLE_RIGHT = '╒' # U+2552
const DOUBLE_TOP_RIGHT = '╗'          # U+2557
const DOUBLE_TOP_RIGHT_SINGLE_DOWN = '╖' # U+2556
const DOUBLE_TOP_RIGHT_SINGLE_LEFT = '╕' # U+2555
const DOUBLE_BOTTOM_LEFT = '╚'        # U+255A
const DOUBLE_BOTTOM_LEFT_SINGLE_UP = '╙' # U+2559
const DOUBLE_BOTTOM_LEFT_SINGLE_RIGHT = '╘' # U+2558
const DOUBLE_BOTTOM_RIGHT = '╝'       # U+255D
const DOUBLE_BOTTOM_RIGHT_SINGLE_UP = '╜' # U+255C
const DOUBLE_BOTTOM_RIGHT_SINGLE_LEFT = '╛' # U+255B
const DOUBLE_TEE_LEFT = '╠'           # U+2560
const DOUBLE_TEE_LEFT_SINGLE_UP_DOWN = '╟' # U+255F

# U+256x row
const DOUBLE_TEE_LEFT_SINGLE_DOWN = '╞' # U+255E
const DOUBLE_TEE_RIGHT = '╣'          # U+2563
const DOUBLE_TEE_RIGHT_SINGLE_UP_DOWN = '╢' # U+2562
const DOUBLE_TEE_RIGHT_SINGLE_UP = '╡' # U+2561
const DOUBLE_TEE_UP = '╦'             # U+2566
const DOUBLE_TEE_UP_SINGLE_LEFT_RIGHT = '╥' # U+2565
const DOUBLE_TEE_UP_SINGLE_RIGHT = '╤' # U+2564
const DOUBLE_TEE_DOWN = '╩'           # U+2569
const DOUBLE_TEE_DOWN_SINGLE_LEFT_RIGHT = '╨' # U+2568
const DOUBLE_TEE_DOWN_SINGLE_RIGHT = '╧' # U+2567
const DOUBLE_CROSS = '╬'              # U+256C
const DOUBLE_CROSS_SINGLE_LEFT_RIGHT = '╫' # U+256B
const DOUBLE_CROSS_SINGLE_UP_DOWN = '╪' # U+256A
const ROUNDED_TOP_LEFT = '╭'          # U+256D
const ROUNDED_TOP_RIGHT = '╮'         # U+256E
const ROUNDED_BOTTOM_RIGHT = '╯'      # U+256F

# U+257x row
const ROUNDED_BOTTOM_LEFT = '╰'       # U+2570
const DIAGONAL_UP_RIGHT = '╱'         # U+2571
const DIAGONAL_DOWN_RIGHT = '╲'       # U+2572
const DIAGONAL_CROSS = '╳'            # U+2573
const HORIZONTAL_1 = '╴'              # U+2574
const VERTICAL_1 = '╵'                # U+2575
const HORIZONTAL_2 = '╶'              # U+2576
const VERTICAL_2 = '╷'                # U+2577
const HORIZONTAL_3 = '╸'              # U+2578
const VERTICAL_3 = '╹'                # U+2579
const HORIZONTAL_4 = '╺'              # U+257A
const VERTICAL_4 = '╻'                # U+257B
const HORIZONTAL_5 = '╼'              # U+257C
const VERTICAL_5 = '╽'                # U+257D
const HORIZONTAL_6 = '╾'              # U+257E
const VERTICAL_6 = '╿'                # U+257F

# Convenient aliases for most common characters
const H = HORIZONTAL_LIGHT
const V = VERTICAL_LIGHT
const TL = TOP_LEFT_LIGHT
const TR = TOP_RIGHT_LIGHT
const BL = BOTTOM_LEFT_LIGHT
const BR = BOTTOM_RIGHT_LIGHT
const CROSS = CROSS_LIGHT

# More readable aliases
const HORIZONTAL = HORIZONTAL_LIGHT
const VERTICAL = VERTICAL_LIGHT
const TOP_LEFT = TOP_LEFT_LIGHT
const TOP_RIGHT = TOP_RIGHT_LIGHT
const BOTTOM_LEFT = BOTTOM_LEFT_LIGHT
const BOTTOM_RIGHT = BOTTOM_RIGHT_LIGHT

end # module
